services:
  - type: web
    name: todo-backend
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        value:  mongodb+srv://e-commerce:e-commerce@cluster0.owehs6j.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
